spring.application.name=Product

spring.datasource.url=jdbc:mysql://localhost:3306/products
spring.datasource.username=root
spring.datasource.password=Sanchita@123

spring.jpa.hibernate.ddl-auto=update
server.port=8081

